FROM quay.io/biocontainers/fasttree:2.1.3--h516909a_3

ARG VERSION=2.1.3

LABEL container.base.image="quay.io/biocontainers/fasttree:2.1.3--h516909a_3 "
LABEL software.name="fasttree"
LABEL software.version=${VERSION}
LABEL software.description="fast phylogenetic reconstruction"
LABEL software.website="http://www.microbesonline.org/fasttree/"
LABEL software.documentation="http://www.microbesonline.org/fasttree/"
LABEL software.license=""
LABEL tags="Phylogenetics"

ENTRYPOINT ["FastTree"]

