FROM quay.io/biocontainers/spades:3.14.1--h2d02072_1

ARG VERSION=3.14.1

LABEL container.base.image="quay.io/biocontainers/spades:3.14.1--h2d02072_1"
LABEL software.name="spades"
LABEL software.version=${VERSION}
LABEL software.description="Paired read assembly"
LABEL software.website="https://cab.spbu.ru/software/spades/"
LABEL software.documentation="https://cab.spbu.ru/software/spades/"
LABEL software.license="MIT/Expat"
LABEL tags="Genomics, Assembly"

ENTRYPOINT ["spades"]

