FROM quay.io/biocontainers/delly:1.1.6--h6b1aa3f_2

ARG VERSION=0.8.3

LABEL container.base.image="quay.io/biocontainers/delly:1.1.6--h6b1aa3f_2"
LABEL software.name="delly"
LABEL software.version=${VERSION}
LABEL software.description="delly for structural variant calling"
LABEL software.website="http://www.htslib.org"
LABEL software.documentation="http://www.htslib.org/doc/samtools.html"
LABEL software.license="MIT/Expat"
LABEL tags="Genomics"

WORKDIR /scratch

