FROM quay.io/biocontainers/snpeff:4.3.1t--hdfd78af_5

ARG VERSION=4.3.1t--hdfd78af_5

LABEL container.base.image="quay.io/biocontainers/snpeff:4.3.1t--hdfd78af_5"
LABEL software.name="snpEff"
LABEL software.version=${VERSION}
LABEL software.description="freebayes genotyper from BAM/CRAM files"
LABEL software.website="http://www.htslib.org"
LABEL software.documentation="http://www.htslib.org/doc/samtools.html"
LABEL software.license="MIT/Expat"
LABEL tags="Genomics"

WORKDIR /scratch