FROM quay.io/biocontainers/iqtree:2.0.3--h176a8bc_1 

ARG VERSION=2.0.3

LABEL container.base.image="quay.io/biocontainers/iqtree:2.0.3--h176a8bc_1"
LABEL software.name="iqtree"
LABEL software.version=${VERSION}
LABEL software.description="Phylogenetic reconstruction"
LABEL software.website="http://www.iqtree.org/"
LABEL software.documentation="http://www.iqtree.org/doc/"
LABEL software.license="GNU General Public License v2.0"
LABEL tags="IQTree"

ENTRYPOINT ["iqtree"]

