FROM quay.io/biocontainers/bedtools:2.31.0--hf5e1c6e_2

ARG VERSION=2.29.1

LABEL container.base.image="quay.io/biocontainers/bedtools:2.31.0--hf5e1c6e_2"
LABEL software.name="bedtools"
LABEL software.version=${VERSION}
LABEL software.description="for bed file manipulations"
LABEL software.website="http://www.htslib.org"
LABEL software.documentation="http://www.htslib.org/doc/samtools.html"
LABEL software.license="MIT/Expat"
LABEL tags="Genomics"

WORKDIR /scratch