FROM quay.io/biocontainers/picard:2.27.5--hdfd78af_0

ARG VERSION=2.27.5--hdfd78af_0

LABEL container.base.image="quay.io/biocontainer/picard:2.27.5--hdfd78af_0"
LABEL software.name="picard"
LABEL software.version=${VERSION}
LABEL software.description="Java tools for working with NGS data in the BAM format"
LABEL software.website="https://github.com/broadinstitute/picard/"
LABEL software.documentation=""
LABEL software.license="MIT/Expat"
LABEL tags="Genomics"

WORKDIR /scratch

