name: 'Build and push bioinformatic images'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

permissions:
  id-token: write
  contents: read

jobs:
  build_push_db-for-prod-bwa:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-bwa
      workdir: containers/bwa
    secrets: inherit

  build_push_db-for-prod-bcftools:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-bcftools
      workdir: containers/bcftools
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}


  build_push_db-for-prod-bedtools:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-bedtools
      workdir: containers/bedtools
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-biopython:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-biopython
      workdir: containers/biopython
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-delly:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-delly
      workdir: containers/delly
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-fastqc:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-fastqc
      workdir: containers/fastqc
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-freebayes:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-freebayes
      workdir: containers/freebayes
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-gatk:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-gatk
      workdir: containers/gatk
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-kraken:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-kraken
      workdir: containers/kraken
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-mosdepth:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-mosdepth
      workdir: containers/mosdepth
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-perl:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-perl
      workdir: containers/perl
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-samtools:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-samtools
      workdir: containers/samtools
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-snpeff:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-snpeff
      workdir: containers/snpeff
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

  build_push_db-for-prod-sra-tools:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: genomicsworkflow-sra-tools
      workdir: containers/sra-tools
    secrets:
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}